name: Docker Image CI

on:
  workflow_dispatch:
#  push:
#    branches: [ current ]
#  pull_request:
#    branches: [ current ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Checkout repo
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build the Docker image
      uses: docker/build-push-action@v2
      with:
        context: docker/.
        file: docker/Dockerfile
        load: true
        tags: vyos-build:latest
  
  makeiso:
     runs-on: ubuntu-latest
     needs: build
     container: 
       image: vyos-build:latest
       volumes: 
         - ${PWD}:/vyos
       options: --workdir "/vyos" --privileged
     steps:
       - run: ./configure
       - run: sudo make iso
         
