name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ current ]
  pull_request:
    branches: [ current ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build docker/. --file docker/Dockerfile --tag vyos-build:$(date +%s)
  
  makeiso:
     run-on: ubuntu-latest
     steps:
       - docker run --name vyos-builder --privileged -v ${PWD}:/vyos -w="/vyos" vyos-builder sh -c "./configure && make iso"
