name: Docker Image CI

on:
  workflow_dispatch:
#  push:
#    branches: [ current ]
#  pull_request:
#    branches: [ current ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build docker/. --file docker/Dockerfile --tag vyos-build:$(date +%s)
  
  makeiso:
     runs-on: ubuntu-latest
     needs: build
     container: 
       image: vyos-build:$(date +%s)
       volumes: 
         - ${PWD}:/vyos
       options: --workdir "/vyos" --privileged
     steps:
       - run: ./configure
       - run: sudo make iso
         
