name: Docker Image CI

on:
  workflow_dispatch:
#  push:
#    branches: [ current ]
#  pull_request:
#    branches: [ current ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Checkout repo
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
    - name: Build the Docker image
      uses: docker/build-push-action@v2
      with:
        context: docker/.
        file: docker/Dockerfile
        platforms: linux/amd64
        push: true
        tags: docker.pkg.github.com/baydakov-tn/vyos-build:latest
        
  makeiso:
     runs-on: ubuntu-latest
     needs: build
     container: 
       image: docker.pkg.github.com/baydakov-tn/vyos-build:latest
       volumes: 
         - ${PWD}:/vyos
       options: --workdir "/vyos" --privileged
     steps:
       - run: ./configure
       - run: sudo make iso
         
